<?php

/*
 * Script to build prod assets with the right hashes and stuff.
 * This works off output of `npm run build`, which must be run prior this script.
 */

define('ROOT_PATH', dirname(__DIR__));
define('DIST_DIR', ROOT_PATH . '/public/dist');
define('PREFIX', '');

// The index.html file output by npm run build
$indexFile = DIST_DIR . '/index.html';

$dom = new DOMDocument();
$dom->loadHTML('<?xml encoding="UTF-8">' . "\n" . file_get_contents($indexFile));

/** @var DOMElement[] $scriptNodes */
$scriptNodes = $dom->getElementsByTagName('script');
/** @var DOMElement[] $styleNodes */
$styleNodes = $dom->getElementsByTagName('link');

$jsScripts = [];
$cssFiles = [];

foreach ($scriptNodes as $node) {
    $path = $node->getAttribute('src');
    $jsScripts[] = PREFIX . $path;
}

foreach ($styleNodes as $node) {
    if ($node->getAttribute('rel') !== 'stylesheet') {
        continue;
    }
    $path = $node->getAttribute('href');
    $cssFiles[] = PREFIX . $path;
}

$outputArray = [
    'scripts' => $jsScripts,
    'css' => $cssFiles,
];

$phpFileContents = '<' . '?php ' . "\n\n" .
    '/' . '* THIS FILE IS AUTOGENERATED, DO NOT MANUALLY EDIT */' . "\n\n" .
    "return " . var_export($outputArray, true) . ";" .
    "\n";

$assetConfigPath = ROOT_PATH . "/config/asset_config.php";

file_put_contents($assetConfigPath, $phpFileContents);

echo "Asset paths written to $assetConfigPath.\n";
